### ISSUE TITLE
Can RP2040 be supported?

### ISSUE THREAD

**Issue by 01Space** [zosko/NoahFC#1]
Your project is great! I'm very interested. I want to migrate your code to RP2040. What is the current step of your project? I'm looking forward to the GPS home function

**Comment by zosko** [comment]
Hey, firmware is for rev1 PCB board and still ground test is working good, i want to make few tests in the sky soon as possible. Meantime i order boards for rev2 . I have teoreticly RTH coded but i did not  test that still. Its not good idea now to migrate code because is not fully tested. I will let you know when is ready.

**Comment by 01Space** [comment]
thank you! 

I like the iNavTelemetry project very much.
